// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (title, url, feed_id)
VALUES (
    $1,
    $2,
    $3
)

RETURNING id, created_at, updated_at, title, url, description, published_at, feed_id
`

type CreatePostParams struct {
	Title  string
	Url    string
	FeedID uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.Title, arg.Url, arg.FeedID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}

const getPosts = `-- name: GetPosts :many
SELECT posts.id, posts.created_at, posts.updated_at, posts.title, posts.url, posts.description, posts.published_at, posts.feed_id
    FROM posts
    JOIN feed_follows ON posts.feed_id = feed_follows.feed_id
        WHERE feed_follows.user_id = $1
    ORDER BY posts.published_at DESC NULLS LAST
    LIMIT $2
`

type GetPostsParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) GetPosts(ctx context.Context, arg GetPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPosts, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDescription = `-- name: UpdateDescription :one
UPDATE posts
    SET description = $1, updated_at = NOW()
    WHERE id = $2
RETURNING id, created_at, updated_at, title, url, description, published_at, feed_id
`

type UpdateDescriptionParams struct {
	Description string
	ID          uuid.UUID
}

func (q *Queries) UpdateDescription(ctx context.Context, arg UpdateDescriptionParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updateDescription, arg.Description, arg.ID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}

const updatePublishedAt = `-- name: UpdatePublishedAt :one
UPDATE posts
    SET published_at = $1, updated_at = NOW()
    WHERE id = $2
RETURNING id, created_at, updated_at, title, url, description, published_at, feed_id
`

type UpdatePublishedAtParams struct {
	PublishedAt sql.NullTime
	ID          uuid.UUID
}

func (q *Queries) UpdatePublishedAt(ctx context.Context, arg UpdatePublishedAtParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePublishedAt, arg.PublishedAt, arg.ID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}
